var lang_es = {
	usuario:'Usuario',
	password:'Contraseña',
	ingresar:'Ingresar',
	vacas_activas:'Vacas Activas',
	vaca:'Vaca',
	hora:'Hora',
	fecha:'Fecha',
	nuevo_parto:'Nuevo Parto',
	becerros:'Becerros',
	becerro:'Becerro',
	info_vaca:'Info Vaca',
	id_vaca:'ID Vaca',
	lactancia:'Lactancia',
	cc:'CC',
	raza:'Raza',
	higiene:'Higiene del perineo',
	tecnico:'Técnico',
	comienza_parto:'Comienza el parto',
	parto:'Parto',
	dificultad:'Dificultad',
	listo:'Listo',
	macho:'Macho',
	hembra:'Hembra',
	presentacion:'Presentación',
	caravana:'Nº',
	becerros_activos:'Becerros activos',
	muerto:'Muerto',
	calostro:'Calostro',
	calidad:'Calidad',
	cantidad:'Cantidad',
	vigor:'Vigor',
	peso_al_nacer:'Peso al nacer',
	sincronizar:'Sincronizar',
	cancelar:'Cancelar',
	msg_sincronizar:'Sincronización!',
	msg_validad_form:'Complete todo los datos',
	salir:'Salir',
	volver:'Volver',
	cantidad_becerros:'Becerros',
	actualizar:'Actualizar',
	agregar:'Agregar',
	bec_cond_V:'V',
	bec_cond_MF:'MF',
	bec_cond_A:'A',
	bec_cond_P:'P',
	bec_cond_M:'M',
	confirmar:'Confirmar',
	registrar: 'Crear cuenta',
	corral: 'Corral',
	notas: 'Notas',
	tipo: 'Tipo',
	metodo: 'Método',
	tc_fresco: 'FR',
	tc_congelado: 'CO',
	tc_sustituto: 'SU',
	mc_tubo: 'TU',
	mc_botella: 'BO',
	vacas_frescas: 'Vacas Frescas',
	complete_todo_los_campos: 'Complete todos los campos.',
	error_login: 'Datos iconrrectos, intente nuevamente.'
};

var lang_en = {
	usuario:'Username',
	password:'Password',
	ingresar:'Login',
	vacas_activas:'Active cows',
	vaca:'Cow',
	hora:'Time',
	fecha:'Date',
	nuevo_parto:'New Calving',
	becerros:'Calves',
	becerro:'Calf',
	info_vaca:'Cow Info',
	id_vaca:'Cow ID',
	lactancia:'Lactation',
	cc:'BCS',
	raza:'Breed',
	higiene:'Perineum Hygiene',
	tecnico:'Personel',
	comienza_parto:'Start calving',
	parto:'Calving',
	dificultad:'Difficulty',
	listo:'Done',
	macho:'Male',
	hembra:'Female',
	presentacion:'Presentation',
	caravana:'Calf ID',
	becerros_activos:'Active calves',
	muerto:'Dead',
	calostro:'Colostrum',
	calidad:'Quality',
	cantidad:'Quantity',
	vigor:'Vigor',
	peso_al_nacer:'Birth weight',
	sincronizar:'Synchronize',
	cancelar:'Cancel',
	msg_sincronizar:'Synchronize!',
	msg_validad_form:'Complete all data',
	salir:'Exit',
	volver:'Back',
	cantidad_becerros:'Calves',
	actualizar:'Update',
	agregar:'Add',
	bec_cond_V:'A',
	bec_cond_MF:'MF',
	bec_cond_A:'Ab',
	bec_cond_P:'P',
	bec_cond_M:'D',
	confirmar:'Confirm',
	registrar: 'Create an account',
	corral: 'Pen',
	notas: 'Notes',
	tipo: 'Type',
	metodo: 'Method',
	tc_fresco: 'FR',
	tc_congelado: 'FZ',
	tc_sustituto: 'SU',
	mc_tubo: 'TU',
	mc_botella: 'BO',
	vacas_frescas: 'Fresh Cows',
	complete_todo_los_campos: 'Please, complete all fields.',
	error_login: 'Your password or username is incorrect, please try again.'
};

if(!localStorage.idioma||localStorage.idioma=='es') var lang=lang_es;
else var lang=lang_en;
